apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: mage-idp-ldap-ui
  name: mage-idp-ldap-ui
spec:
  ports:
    - name: "6480"
      port: 6480
      targetPort: 80
    - name: "6443"
      port: 6443
      targetPort: 443
  selector:
    io.kompose.service: mage-idp-ldap-ui
